#!/usr/bin/env bash
set -eu

# http://stackoverflow.com/questions/9080431/how-execute-bash-script-line-by-line
# set -x
# trap read debug

declare -r SCRIPTPATH=$(realpath "$0")
declare -r SCRIPTDIR=$(dirname "$SCRIPTPATH")
declare -r ROOT="$(realpath "$SCRIPTDIR/../..")"

declare -r WORK_DIR="${TMPDIR}brenda-work"
export RENDER_OUTPUT="s3://sh-brenda"
export BRENDA_CONFIG="$ROOT/test/brenda.conf"

# Setup work dir
rm -rvf "$WORK_DIR"
mkdir -pv "$WORK_DIR"
cp -av "$ROOT/test/tasks/"*".py" "$WORK_DIR"

# Setup render output
aws s3 rm "$RENDER_OUTPUT" --recursive

# Run Brenda
"$ROOT/brenda-work" reset
"$ROOT/brenda-work" status

"$ROOT/brenda-work" --end 9 --task-script "$ROOT/test/tasks/task-perframe" push
"$ROOT/brenda-node" -c "$BRENDA_CONFIG"
