#!/opt/local/bin/bash
set -eu

export RENDER_OUTPUT="s3://sh-brenda"
declare -r LS_FILE="s3-ls.txt"

# Check S3 output
aws s3 ls "$RENDER_OUTPUT" > "$LS_FILE"
cat "$LS_FILE"
wc "$LS_FILE"
rm "$LS_FILE"
