#!/opt/local/bin/bash
# Push chaos task to test brenda-node while in poll mode.
set -eu

declare -r SCRIPTPATH=$(realpath "$0")
declare -r SCRIPTDIR=$(dirname "$SCRIPTPATH")
declare -r ROOT="$(realpath "$SCRIPTDIR/../..")"

export BRENDA_CONFIG="$ROOT/test/brenda.conf"
"$ROOT/brenda-work" --end 4 --task-script "$ROOT/test/tasks/task-chaos" push